# Generated by Django 2.2.dev20181125194326 on 2019-07-08 17:06

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pubganalyticData',
            fields=[
                ('requester', models.CharField(max_length=100)),
                ('pubg_name', models.CharField(default='', max_length=100)),
                ('requested', models.DateTimeField(default=datetime.datetime(2019, 7, 8, 17, 6, 50, 83869), verbose_name='Date requested')),
                ('requestID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
