# Generated by Django 2.2.dev20181125194326 on 2019-07-08 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubganalytic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubganalyticdata',
            name='requested',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 8, 17, 7, 5, 611510), verbose_name='Date requested'),
        ),
    ]
