# Generated by Django 2.2.dev20181125194326 on 2019-07-08 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataanalyzeAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('published', models.DateTimeField(default=datetime.datetime(2019, 7, 8, 17, 6, 50, 82438), verbose_name='Date published')),
                ('summary', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Data Analyze',
            },
        ),
    ]
